apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      containers:
      - name: devops-hello-world
        image: devops:test
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: {{MEMORY}}
          requests:
            memory: {{MEMORY}}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 120
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 120
        volumeMounts:
          - name: config-volume
            mountPath: /opt/config/application.properties
            subPath: application.properties
      volumes:
        - name: config-volume
          configMap:
            name: hello-world-config